"use client";

import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen px-6 py-16">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="inline-block mb-8">
          <span className="font-headline text-2xl" style={{ color: "var(--foreground)" }}>
            The<span className="accent-text">Auctus</span>
          </span>
        </Link>
        <h1 className="font-headline text-4xl mb-4" style={{ color: "var(--foreground)" }}>Terms of Service</h1>
        <p className="text-[12px] mb-12" style={{ color: "var(--muted)" }}>Last updated: August 24, 2026</p>

        <div className="space-y-10 text-[13px] leading-relaxed" style={{ color: "var(--muted)" }}>
          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>1. Acceptance of Terms</h2>
            <p>
              By accessing or using TheAuctus (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>2. Description of Service</h2>
            <p>
              TheAuctus is an AI-powered content planning and publishing platform for creators. The Service includes
              content generation, scheduling, analytics, and growth tools.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>3. Account Registration</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must be at least 13 years old to use the Service</li>
              <li>You must provide accurate and complete registration information</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must notify us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>4. Subscriptions and Payments</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong style={{ color: "var(--foreground)" }}>Free trial:</strong> 14 days, no credit card required</li>
              <li><strong style={{ color: "var(--foreground)" }}>Billing:</strong> Subscriptions renew automatically unless cancelled</li>
              <li><strong style={{ color: "var(--foreground)" }}>Refunds:</strong> Full refund within 7 days of initial purchase</li>
              <li><strong style={{ color: "var(--foreground)" }}>Price changes:</strong> We will notify you 30 days before any price increase</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>5. Content Ownership</h2>
            <p className="mb-3">
              <strong style={{ color: "var(--foreground)" }}>Your content:</strong> You retain all rights to content you create using the Service.
              TheAuctus does not claim ownership of your content.
            </p>
            <p>
              <strong style={{ color: "var(--foreground)" }}>AI-generated content:</strong> Content generated by AI based on your inputs is yours to use.
              We do not use your content to train AI models without explicit consent.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>6. Acceptable Use</h2>
            <p className="mb-3">You agree NOT to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Service for illegal purposes</li>
              <li>Generate spam, misleading, or harmful content</li>
              <li>Circumvent usage limits or rate restrictions</li>
              <li>Reverse engineer or decompile the Service</li>
              <li>Resell or redistribute the Service without permission</li>
              <li>Violate platform terms of service (Twitter, Instagram, etc.)</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>7. Third-Party Integrations</h2>
            <p>
              The Service connects to third-party platforms (Twitter, Instagram, LinkedIn, etc.).
              Your use of these integrations is subject to their respective terms of service.
              We are not responsible for third-party platform actions or policies.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>8. Limitation of Liability</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES. We are not liable for any indirect,
              incidental, or consequential damages. Our total liability shall not exceed the amount paid
              by you in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>9. Termination</h2>
            <p>
              We may suspend or terminate your account for violation of these Terms. You may cancel your
              subscription at any time. Upon termination, your data will be deleted within 30 days.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>10. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Material changes will be notified via email
              or in-app notification. Continued use constitutes acceptance of updated Terms.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>11. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of California, without regard to
              conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-xl mb-3" style={{ color: "var(--foreground)" }}>12. Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:legal@theauctus.in" className="accent-text hover:opacity-80">legal@theauctus.in</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
